/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan;


import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;


/**
 *
 * @author USER
 */
//import javax.swing.JOptionpane;
//import javax.swing.table.DefaultTableModel;
public class tiket extends javax.swing.JFrame {
    int ekonomi, bisnis, frist ,bayar, total, harga, beli, kembali, jawab,cetak;
    int x=0;
    String kelas,tujuan;
    /**
     * Creates new form tiket
     */
   
    public tiket() {
        initComponents();
     
        
        JOptionPane.showMessageDialog(null, "SELAMAT DATANG DI PEMESANAN TIKET PESAWAT SSS-AIR");
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if(frameSize.height > screenSize.height){
            frameSize.height = screenSize.height;
        }
        if(frameSize.width > screenSize.width){
            frameSize.width = screenSize.width;
        }
        this.setLocation(
                (screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
        
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbmdestinasi = new javax.swing.JComboBox<>();
        txtnopenerbangan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbekonomi = new javax.swing.JRadioButton();
        rbbisnis = new javax.swing.JRadioButton();
        rbfristclass = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtmaskapai = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txttanggal = new javax.swing.JTextField();
        txtjam = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtnoidentitas = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        txttotalharga = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        txtkembalian = new javax.swing.JTextField();
        btnbelilagi = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnbeli = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbbeli = new javax.swing.JTable();
        bthapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 255, 204));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MingLiU-ExtB", 1, 18)); // NOI18N
        jLabel1.setText("PEMESANAN TIKET  PESAWAT SSS-AIR");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "MASKAPAI"));

        jLabel2.setText("DESTINASI");

        jLabel3.setText("NAMA MASKAPAI");

        jLabel4.setText("NO.PENERBANGAN");

        cbmdestinasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "===PILIH===", "JAKARTA - PONTIANAK", "PONTIANAK - JAKARTA", "PONTIANAK - BANDUNG", "BANDUNG - PONTIANAK", "JAKARTA - SURABAYA", "PONTIANAK - MEDAN", "PALEMBANG - PONTIANAK", " ", " " }));
        cbmdestinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmdestinasiActionPerformed(evt);
            }
        });

        jLabel5.setText("KELAS");

        rbekonomi.setBackground(new java.awt.Color(51, 255, 204));
        rbekonomi.setText("EKONOMI");
        rbekonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbekonomiActionPerformed(evt);
            }
        });

        rbbisnis.setBackground(new java.awt.Color(51, 255, 204));
        rbbisnis.setText("BISNIS");
        rbbisnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbisnisActionPerformed(evt);
            }
        });

        rbfristclass.setBackground(new java.awt.Color(51, 255, 204));
        rbfristclass.setText("FIRST CLASS");
        rbfristclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfristclassActionPerformed(evt);
            }
        });

        jLabel6.setText("HARGA");

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });

        jLabel7.setText("Rp.");

        jLabel15.setText("TANGGAL KEBERANGKATAN");

        jLabel16.setText("JAM KEBERANGKATAN");

        jLabel17.setText("WIB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel15)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel16)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbekonomi)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtjam, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))
                            .addComponent(cbmdestinasi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnopenerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbbisnis)
                            .addComponent(rbfristclass)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txttanggal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtmaskapai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbmdestinasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnopenerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbekonomi)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbbisnis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbfristclass)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 370, 370));
        jPanel1.getAccessibleContext().setAccessibleName("PESAWAT\n\n");

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "PEMESANAN"));

        jLabel8.setText("NAMA");

        jLabel9.setText("NO.IDENTITAS");

        jLabel10.setText("JUMLAH");

        jLabel11.setText("TOTAL HARGA");

        jLabel12.setText("UANG BAYAR");

        jLabel13.setText("UANG KEMBALI");

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        txtnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnamaKeyTyped(evt);
            }
        });

        txtnoidentitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoidentitasActionPerformed(evt);
            }
        });
        txtnoidentitas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnoidentitasKeyTyped(evt);
            }
        });

        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });
        txtjumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjumlahKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtjumlahKeyTyped(evt);
            }
        });

        txttotalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalhargaActionPerformed(evt);
            }
        });

        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbayarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbayarKeyTyped(evt);
            }
        });

        txtkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembalianActionPerformed(evt);
            }
        });
        txtkembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkembalianKeyReleased(evt);
            }
        });

        btnbelilagi.setText("REFRESH");
        btnbelilagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbelilagiActionPerformed(evt);
            }
        });

        jLabel14.setText("TIKET");

        btnbeli.setText("BELI");
        btnbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeliActionPerformed(evt);
            }
        });

        jLabel18.setText("Rp.");

        jLabel19.setText("Rp.");

        jLabel20.setText("Rp.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtkembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(txtnoidentitas)
                                    .addComponent(txtnama))
                                .addGap(33, 33, 33))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel14))
                                            .addComponent(txttotalharga)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnbelilagi)
                        .addGap(78, 78, 78))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtnoidentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txttotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbeli)
                    .addComponent(btnbelilagi))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 370, 360));

        tbbeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NAMA", "NO.IDENTITAS", "NAMA MASKAPAI", "NO.PENERBANGAN", "DESTINASI", "TANGGAL KEBERANGKATAN", "JAM KEBERANGKATAN"
            }
        ));
        jScrollPane3.setViewportView(tbbeli);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 870, 120));

        bthapus.setText("HAPUS DATA");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        jPanel2.add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 140, -1));

        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel2.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 620, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbbisnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbisnisActionPerformed
        // TODO add your handling code here:
          if(rbbisnis.isSelected()){
            txtharga.setText(String.valueOf(bisnis));
            rbekonomi.setSelected(false);
            rbfristclass.setSelected(false);
        }
        
    }//GEN-LAST:event_rbbisnisActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkembalianActionPerformed

    private void cbmdestinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmdestinasiActionPerformed
        // TODO add your handling code here:
        if(cbmdestinasi.getSelectedItem().equals("===PILIH===")){
            buttonGroup1.clearSelection();
            txtmaskapai.setText("");
            txtnopenerbangan.setText("");
            txtharga.setText("");
        }
        else if(cbmdestinasi.getSelectedItem().equals("JAKARTA - PONTIANAK")){
            txtmaskapai.setText("GARUDA INDONESIA");
            txtnopenerbangan.setText("09-GA890");
            txttanggal.setText("6 MAI 2020");        
            txtjam.setText("13:40");
            ekonomi=1450000;
            bisnis=1560000;
            frist=2125000; 
        }
        else if(cbmdestinasi.getSelectedItem().equals("PONTIANAK - JAKARTA")){
            txtmaskapai.setText("GARUDA INDONESIA");
            txtnopenerbangan.setText("09-GA890");
            txttanggal.setText("1 JUNI 2020");        
            txtjam.setText("11:40");
            ekonomi=1400000;
            bisnis=1450000;
            frist=1865000; 
        }
        else if(cbmdestinasi.getSelectedItem().equals("PONTIANAK - BANDUNG")){
            txtmaskapai.setText("BATIK AIR");
            txtnopenerbangan.setText("03-BA770");
            txttanggal.setText("13 JUNI 2020");        
            txtjam.setText("08:10");
            ekonomi=1500000;
            bisnis=2000000;
            frist=2500000; 
        }
        else if(cbmdestinasi.getSelectedItem().equals("BANDUNG - PONTIANAK")){
            txtmaskapai.setText("SRIWIJAYA AIR");
            txtnopenerbangan.setText("01-SJ554");
            txttanggal.setText("10 JUNI 2020");        
            txtjam.setText("09:10");
            ekonomi=800000;
            bisnis=1550000;
            frist=1850000; 
        }
        else if(cbmdestinasi.getSelectedItem().equals("JAKARTA - SURABAYA")){
            txtmaskapai.setText("BATIK AIR");
            txtnopenerbangan.setText("03-BA870");
            txttanggal.setText("19 JULI 2020");        
            txtjam.setText("15:30");
            ekonomi=1700000;
            bisnis=1950000;
            frist=2150000; 
        }
        else if(cbmdestinasi.getSelectedItem().equals("PONTIANAK - MEDAN")){
            txtmaskapai.setText("LION AIR");
            txtnopenerbangan.setText("09-LN871");
            txttanggal.setText("17 JUNI 2020");        
            txtjam.setText("13:40");
            ekonomi=1550000;
            bisnis=1950000;
            frist=2150000; 
        }
        else if(cbmdestinasi.getSelectedItem().equals("PALEMBANG - PONTIANAK")){
            txtmaskapai.setText("SRIWIJAYA AIR");
            txtnopenerbangan.setText("01-SJ765");
            txttanggal.setText("3 JUNI 2020");        
            txtjam.setText("19:40");
            ekonomi=1558000;
            bisnis=2100000;
            frist=2585000; 
        }
        
    }//GEN-LAST:event_cbmdestinasiActionPerformed

    private void txttotalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalhargaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txttotalhargaActionPerformed

    private void rbekonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbekonomiActionPerformed
        // TODO add your handling code here:
        if(rbekonomi.isSelected()){
            txtharga.setText(String.valueOf(ekonomi));
            rbbisnis.setSelected(false);
            rbfristclass.setSelected(false);
        }
    }//GEN-LAST:event_rbekonomiActionPerformed

    private void rbfristclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfristclassActionPerformed
        // TODO add your handling code here:
          if(rbfristclass.isSelected()){
            txtharga.setText(String.valueOf(frist));
            rbekonomi.setSelected(false);
            rbbisnis.setSelected(false);{
       
          }     
        }
    }//GEN-LAST:event_rbfristclassActionPerformed

    private void btnbelilagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbelilagiActionPerformed
        // TODO add your handling code here:
        cbmdestinasi.setSelectedItem("===PILIH===");
        rbekonomi.setSelected(false);
        rbbisnis.setSelected(false);
        rbfristclass.setSelected(false);
        txtmaskapai.setText("");
        txtnopenerbangan.setText("");
        txttanggal.setText("");
        txtjam.setText("");
        txtharga.setText("");
        txtnama.setText("");
        txtnoidentitas.setText("");
        txtjumlah.setText("");
        txttotalharga.setText("");
        txtbayar.setText("");
        txtkembalian.setText("");
    }//GEN-LAST:event_btnbelilagiActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
        int jawab= JOptionPane.showConfirmDialog(null, "APAKAH ANDA INGIN KELUAR","KELUAR", JOptionPane.OK_OPTION);
        if(jawab==JOptionPane.OK_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        // TODO add your handling code here:
       beli=Integer.parseInt(txtjumlah.getText());
       harga=Integer.parseInt(txtharga.getText());
       total=bayar*harga;
       txttotalharga.setText(String.valueOf(total));
    }//GEN-LAST:event_txtjumlahActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        // TODO add your handling code here:
       beli=Integer.parseInt(txtbayar.getText());
       kembali=Integer.parseInt(txttotalharga.getText());
       total=bayar-kembali;
       txtkembalian.setText(String.valueOf(total));
    }//GEN-LAST:event_txtbayarActionPerformed

    private void txtjumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a=Integer.valueOf(txtharga.getText());
        b=Integer.valueOf(txtjumlah.getText());
        c=a*b;
        txttotalharga.setText(""+c);
    }//GEN-LAST:event_txtjumlahKeyReleased

    private void txtkembalianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkembalianKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkembalianKeyReleased

    private void txtbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a=Integer.valueOf(txtbayar.getText());
        b=Integer.valueOf(txttotalharga.getText());
        c=a-b;
        txtkembalian.setText(""+c);
    }//GEN-LAST:event_txtbayarKeyReleased

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txthargaActionPerformed

    private void btnbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeliActionPerformed
        // TODO add your handling code here:
//        String destinasi = (String) cbmdestinasi.getSelectedItem();
//        if(txtnama.getText().isEmpty()||cbmdestinasi.getSelectedItem().toString().isEmpty()||txtnoidentitas.getText().isEmpty()||
//           txtjumlah.getText().isEmpty()||txtbayar.getText().isEmpty()){
//           JOptionPane.showMessageDialog(null,"EROR : SETIAP DATA HARUS DIISI","PESAN KESALAHAN",JOptionPane.WARNING_MESSAGE);}
        
       tbbeli.setValueAt(txtnama.getText(),x,0);
       tbbeli.setValueAt(txtnoidentitas.getText(),x,1);
       tbbeli.setValueAt(txtmaskapai.getText(),x,2);
       tbbeli.setValueAt(txtnopenerbangan.getText(),x,3);
       tbbeli.setValueAt(cbmdestinasi.getSelectedItem(),x,4);
       tbbeli.setValueAt(txttanggal.getText(),x,5);
       tbbeli.setValueAt(txtjam.getText(),x,6);
       x=x+1;
    }//GEN-LAST:event_btnbeliActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        tbbeli.setValueAt("", tbbeli.getSelectedRow(), 0);
        tbbeli.setValueAt("", tbbeli.getSelectedRow(), 1);
        tbbeli.setValueAt("", tbbeli.getSelectedRow(), 2);
        tbbeli.setValueAt("", tbbeli.getSelectedRow(), 3);
        tbbeli.setValueAt("", tbbeli.getSelectedRow(), 4);
        tbbeli.setValueAt("", tbbeli.getSelectedRow(), 5);
        tbbeli.setValueAt("", tbbeli.getSelectedRow(), 6);
    }//GEN-LAST:event_bthapusActionPerformed

    private void txtnoidentitasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnoidentitasKeyTyped
        // TODO add your handling code here:||
        char x = evt.getKeyChar();
        if (!(Character.isDigit(x) || x == KeyEvent.VK_BACK_SPACE || x == KeyEvent.VK_DELETE )){
            evt.consume();
        }
    }//GEN-LAST:event_txtnoidentitasKeyTyped

    private void txtnamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamaKeyTyped
        // TODO add your handling code here:
        char x = evt.getKeyChar();
        if ((Character.isDigit(x) || x == KeyEvent.VK_BACK_SPACE || x == KeyEvent.VK_DELETE )){
            evt.consume();
        }
    }//GEN-LAST:event_txtnamaKeyTyped

    private void txtnoidentitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoidentitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoidentitasActionPerformed

    private void txtbayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyTyped
        // TODO add your handling code here:
        char x = evt.getKeyChar();
        if (!(Character.isDigit(x) || x == KeyEvent.VK_BACK_SPACE || x == KeyEvent.VK_DELETE )){
            evt.consume();
        }
    }//GEN-LAST:event_txtbayarKeyTyped

    private void txtjumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahKeyTyped
        // TODO add your handling code here:
        char x = evt.getKeyChar();
        if (!(Character.isDigit(x) || x == KeyEvent.VK_BACK_SPACE || x == KeyEvent.VK_DELETE )){
            evt.consume();
        }
    }//GEN-LAST:event_txtjumlahKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btnbeli;
    private javax.swing.JButton btnbelilagi;
    private javax.swing.JButton btnkeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbmdestinasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbbisnis;
    private javax.swing.JRadioButton rbekonomi;
    private javax.swing.JRadioButton rbfristclass;
    private javax.swing.JTable tbbeli;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjam;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtmaskapai;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnoidentitas;
    private javax.swing.JTextField txtnopenerbangan;
    private javax.swing.JTextField txttanggal;
    private javax.swing.JTextField txttotalharga;
    // End of variables declaration//GEN-END:variables
}
